server:
    port: 9002
    servlet:
        context-path: /onboarding

# application configuration
spring:
    application:
        name: customer-onboarding-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/customerprofiledb?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
    jackson:
        default-property-inclusion: non-null

# eureka server configuration
eureka:
    client:
        service-url:
            defaultZone: http://localhost:4001/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        hostname: localhost
        prefer-ip-address: true

# enabling actuator info
management:
    endpoints:
        health:
            show-details: always
        web:
            exposure:
                include: '*'
